# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_udate',
            new_name='pub_date',
        ),
    ]
